- jwst/build.sh
Addresses headerpadding on both Darwin and Linux.
> Convert case to one-liner

- readline/build.sh
- readline/meta.yaml
- readline/ncurses.patch
- readline/tpn.patch
`readline` indev will not be updated to match further developments from Continuum. However, this critical revision fixes the broken ncurses linkage under Linux.
> Add readline (workaround)

- hstcal/meta.yaml
MD5 mismatch on OSX. Trying to correct for it.
> Rebuild hstcal

- astropy/meta.yaml
Apparently astropy's scripts require `pytest` to exist.
Seems like a bug to me.
> Add pytest as runtime dependency

- astropy/meta.yaml
```python
+ samp_hub --help
WARNING: AstropyDeprecationWarning: The astropy.samp module has now been moved to astropy.samp [astropy.vo.samp]
Traceback (most recent call last):
File "/Users/shared/iraf_conda/bldtmp/p3wX/p/conda-bld/astropy_1498636857655/_t_env/bin/samp_hub", line 11, in <module>
load_entry_point('astropy==3.0.dev19488', 'console_scripts', 'samp_hub')()
File "/Users/shared/iraf_conda/bldtmp/p3wX/p/conda-bld/astropy_1498636857655/_t_env/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 565, in load_entry_point
File "/Users/shared/iraf_conda/bldtmp/p3wX/p/conda-bld/astropy_1498636857655/_t_env/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
File …
```
> Remove deprecated samp_hub smoketest

- spherical-geometry/meta.yaml
Match package name with existing PyPI package `spherical-geometry`. Decouple package name from repository name to accommodate previous naming decisions.
> Hyphenate package name

- asdf/meta.yaml
Fixes recent build failure:
```python
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/semantic_version/r
```
CC @nden @drdavella
> [asdf] Add missing semantic_version dependency

- pymssql/0001-Drop-usage-of-DBVERSION_80-symbol-d90c9b.patch
- pymssql/0002-Change-setup_requires-setuptools_git-to-setuptools.patch
- pymssql/0003-Use-libsybdb-not-db-lib-since-I-renamed-it.patch
- pymssql/0004-Win32-link-to-openssl.patch
- pymssql/bld.bat
- pymssql/build.sh
- pymssql/meta.yaml
**Reason we are building it:** 
- Continuum has abandoned this recipe upstream
- JWST pipeline requires it
**Notes:**
I yanked this from `conda/conda-recipes` and modified it. The patches have been adjusted to work with 2.1.3, because someone injected patches against an unreleased version of `pymssql` using a different directory structure. 🎱
> Initial commit of pymssql

- jwst/meta.yaml
Recently added to source base; wasn't informed.
> JWST: Add matplotlib as build dependency

- pyobjc-core/build.sh
- pyobjc-framework-cocoa/build.sh
- pyobjc-framework-quartz/build.sh
`conda-build` fails to adjust RPATHs unless `-headerpad_max_install_names` is enabled.
> pyobjc: Enforce rpath padding

- hstcal/build.sh
Trying to avoid hundreds of thousands of:
```
error: register %rXX is only available in 64-bit mode
```
> hstcal: [Darwin] Force 64-bit linking

- dbus-python/build.sh
Failed to find `python2.7.so` during compilation of `dbus-python`. Setting C/LD flags corrects the issue. This did not happen while building against Python 3.
> [py27 fix] Force shared library discovery.

- astropy/meta.yaml
Prevents nonsensical Jenkins builds.
> [astropy] Python 2.7 support dropped upstream. Skipping.

- sextractor/build.sh
- sextractor/meta.yaml
* Install autotools regardless of platform (RHEL 6 is aging. No surprise there.)
* m4 was complaining, so re-libtoolize the project before reconfiguring
* Switch download URL to github release mirror. Astromatic's primary site is too slow.
> sextractor: Hopefully final fixup

- sextractor/meta.yaml
Didn't notice due to cached tarball.
`conda-build` package downloading security is tops.
> sextractor: of course the md5 hash changed

- glueviz/meta.yaml
* Override this behavior by "building" with Python. Dumb but effective.
* Warnings added to prevent this situtation from coming up once again.
Rationale:
1. Two packages exist: 0.8.2_py{35,36} and 0.12.0-1
2. `conda install glueviz` finds 0.8.2 because it has py{35,36} in the package name
3. `conda install "glueviz>0.8.2"` installs 0.12.0 because 0.8.2 is no longer considered in the pool of resolved packages
4. Adding `build: - python {{ python }}` and `run: - python` forces `conda-build` to generate a py{VER} package.
> Conda's resolver cannot see glueviz >0.8 as latest package

- stsci.tools/meta.yaml
* `stwcs` depends on `stsci.tools`
* `stsci.tools` does depend on `stwcs`, but oh well.
> stsci.tools: remove circular dependency on stwcs

- acstools/meta.yaml
Fixes regression tests failing due to missing "optional" dependencies.
> Optional dependencies are no longer optional. Do not revert.

- astropy/meta.yaml
This change is for tracking purposes only.
> Upstream astropy/master uses 3.1.dev now

- jwst/meta.yaml
Fixes
```
EXCEPTION
Type: ImportError
Message: No module named 'stwcs'
```
> jwst: Add missing stwcs dependency

- mosviz/build.sh
- specviz/build.sh
Allows packages to build against development version of specutils.
reason: specutils' internal version is 0.1.dev, and the package requires 0.2.2 (or something equivalent on master)
> [mos/spec]viz: Drop specutils 0.2.2 version pinning in setup

- specviz/meta.yaml
Sorry @jhunkeler. This one fell through the cracks.
> Quick fix: add docopt run dependency to specviz recipe

- stsci.tools/bld.bat
- stsci.tools/build.sh
- stsci.tools/meta.yaml
* Also removes `nose` as a run-time dependency and replaces it with `pytest-runner` at compile-time.
> stsci.tools: Remove d2to1 and stsci.distutils dependencies

- fast-histogram/build.sh
- mpl-scatter-density/build.sh
Avoid `UnicodeDecodeErrors`
:sleeping: :zap:
> Truncate READMEs to avoid unicode errors

- cfitsio/meta.yaml
Allowing `libcfitsio` to link against the system's `libcurl` has undesired results on different OSes. Linking against Conda's `curl` should help, but I can't promise Continuum will not break it at some point.
> cfitsio: curl

- jwst/meta.yaml
This PR should only become active **AFTER** [JWST PR #1859](https://github.com/STScI-JWST/jwst/pull/1859) has been merged.
> Replace deprecated sphere package in JWST

- jwst/meta.yaml
```
jwst$ grep -R import | grep -E 'stwcs|fitsblender'
jwst/assign_wcs/tests/test_nirspec.py:from astropy import wcs as astwcs
#
```
> jwst: Purge unused dependencies

- jwst/meta.yaml
`timeconversion` step failed due to missing `pymssql` under Python 3.6.
> jwst: remove pymssql constraint

- cfitsio/0001-cfitsio-autoconf-disable-curl.patch
- cfitsio/build.sh
- cfitsio/meta.yaml
- crds/meta.yaml
- fitsverify/meta.yaml
- hstcal/meta.yaml
- stsci/meta.yaml
Conda's `curl` is broken and a system-level `libcurl` is not guaranteed to exist.
Here's the compromise:
This patch adds `--disable-curl` to the autoconf script so we can turn it off at will. If we figure out a better way to link against curl in the future, maybe we can re-enable it. Until then anyone using this build will not be able to open SSL encrypted streams via native `cfitsio` calls.
We (STScI) do not use the remote API calls in `cfitsio`. 
Sorry if this is an inconvenience to anyone in the community.
If you *need* HTTPS support feel free to edit `build.sh` locally and remove `--disable-curl` from the configuration line. Then execute `conda build` against this recipe. (We cannot offer support for what comes out the other side should you do this. Your mileage may vary.)
cc …
> Cfitsio disable curl

- specviz/build.sh
- specviz/meta.yaml
`(pyqt5 || PyQt5) != pyqt >=5.0.0`
Thanks Conda.
> specviz: circumvent pyqt5 dependency

- conda_build_config.yaml
Bumping `numpy` base to match what's available/compatible in the channel (`np11[1,4,5]`). 
---
👦 : Santa, why are you inconsistent with the presents you give to children from year to year?
🎅 : Ho ho ho! Oh child... Wouldn't you like to know!
> Add 3.7 to conda_build_config.yaml

- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci/meta.yaml
This was done in public but somehow not in dev.
> Tie each metapackage to its respective python version

- stsci-data-analysis/meta.yaml
- stsci-hst/meta.yaml
- stsci/meta.yaml
* Remove totally deprecated dependencies
* Future: If recipe no longer exists... remove from metapackage
Build revision bumped across all metapackages to ensure rebuilds.
> Fix py37 package resolution failures

- astropy-healpix/meta.yaml
Cannot build under 3.7 without newer `setuptools`.
- Might affect 3.6 if that pesky `cython` segfault still exists. We'll find out.
> astropy-healpix: Remove setuptools pin

- stistools/meta.yaml
> stistools: Fix broken dependencies

- jwst/meta.yaml
Also remove `dask`, `six` and `pytest-remotedata`, as these are not required or used.
Resolves #167.
> Add ci_watson to jwst build recipe

- ds9/meta.yaml
Move ds9 version to latest release.
@jhunkeler @rendinam not sure if the md5 hash also needs to be updated.
> update ds9 to v8.0

- hlapipeline/meta.yaml
Removing unused pyyaml dependency to fix conda build failures.
> removed pyyaml from recipe

- jwst/meta.yaml
Conda made a package of `jsonschema 3.0` yesterday and broke the `jwst` package, which really needs `>=2.3,<=2.6` (due to `asdf`):
```
$ firewatch -t 2d | grep jsonschema
2019-03-11T16:32:36 : main/osx-64 : jsonschema-3.0.1-py27_0.tar.bz2         
2019-03-11T16:40:13 : main/osx-64 : jsonschema-3.0.1-py37_0.tar.bz2         
2019-03-11T16:40:45 : main/osx-64 : jsonschema-3.0.1-py36_0.tar.bz2         
```
Also, removing 2 dependencies that are no longer needed - `stsci.tools` and `namedlist`.
> Pin jsonschema <=2.6

- asdf/meta.yaml
The requirements here should now match those in `astroconda-contrib`.
> Fix asdf dependencies. Reflect jsonschema<=2.6

- stsci-hst/meta.yaml
> Remove outdated/deprecated stsci.sphinxext from HST metapackage

- jwst/meta.yaml
This submodule import smoke test is now moved to the package unit tests of `jwst` itself, so no need to do it here.  And we would like to remove `steps.py` as it now serves no purpose.
See https://github.com/spacetelescope/jwst/pull/3561
> Remove jwst.steps from import test in jwst recipe
