jplephem/0001_use-setuptools.patch, jplephem/bld.bat, jplephem/build.sh, jplephem/meta.yaml
=> Initial commit of jplephem

stsci-data-analysis/meta.yaml, stsci-hst/meta.yaml, stsci/meta.yaml
Also removes DA tools from top-level metapackage
=> Attempt to force resolver to pick up the latest packages

jwxml/bld.bat, jwxml/build.sh, jwxml/meta.yaml
Missing recipe dependency for poppy/webbpsf
=> Initial commit of jwxml

astropy/meta.yaml
=> Allow py36

fitsverify/bld.bat, fitsverify/build.sh, fitsverify/meta.yaml
@jaytmiller Adding fitsverify per your request
=> Initial commit of fitsverify

fitsverify/meta.yaml
=> Fix incorrect pkg-config dep; bump build

purge_path/meta.yaml
=> Update purge_path repository URL

parsley/meta.yaml
Relates to https://github.com/astroconda/astroconda-contrib/pull/214
=> Fix package naming typo

crds/build.sh, crds/meta.yaml
Relates to: https://github.com/astroconda/astroconda-contrib/pull/215
=> CRDS: Add optional dependencies

htc_utils/meta.yaml
Clearly I missed the `git_url`
=> htc_utils: actually change URL

stsci.sphere/meta.yaml
(Yes I know the package is deprecated.)
=> [stsci.sphere] Fix broken link

py-expression-eval/bld.bat, py-expression-eval/build.sh, py-expression-eval/meta.yaml
=> Initial commit of py-expression-eval

ds9/build.sh, ds9/meta.yaml
Port of James Turner's modifications from contrib to dev.
=> [ds9] Disable xscreensaver support

namedlist/bld.bat, namedlist/build.sh, namedlist/meta.yaml
=> Initial commit of namedlist

jwst/meta.yaml
=> [jwst] Add namedlist dependency

namedlist/meta.yaml
=> [namedlist] Fix summary

astroquery/bld.bat, astroquery/build.sh, astroquery/meta.yaml
=> Initial commit; astroquery

glue-core/LICENSE, glue-core/meta.yaml, glue-ginga/bld.bat, glue-ginga/build.sh, glue-ginga/meta.yaml, glue-vispy-viewers/LICENSE, glue-vispy-viewers/meta.yaml, glueviz/LICENSE, glueviz/meta.yaml
=> Backport from contrib

glueviz/meta.yaml
"Sleek and special" is not sleek, but special
=> Fix recipe

specviz/meta.yaml
Add missing build section to specviz recipe.
=> Add build section

stsci.tools/meta.yaml
=> stsci.tools: Add missing runtime dependencies

cubeviz/meta.yaml
Also add dependency on `spectral-cube`.
=> Cubeviz: use glue-core as dependency instead of glueviz

radio-beam/bld.bat, radio-beam/build.sh, radio-beam/meta.yaml
@drdavella 
Handle dependency of #99
=> Add radio-beam

spectral-cube/bld.bat, spectral-cube/build.sh, spectral-cube/meta.yaml
=> Create new recipe for spectral-cube

mosviz/meta.yaml
This will squelch the relentless failures we've been seeing.
=> Replace glueviz with glue-core

astropy/meta.yaml
`3.0.0` was officially released today.
Tracking `4.0.0`...
=> astropy: track next major release

drizzlepac/meta.yaml
=> drizzlepac: requires nose

crds/meta.yaml
Tracking https://github.com/astroconda/astroconda-contrib/pull/373
=> crds: Update dependencies

cfitsio/build.sh, cfitsio/meta.yaml
Ref:
https://github.com/spacetelescope/hstcal/issues/325
=> cfitsio: Help prevent linkage against conda libcurl

hstcal/meta.yaml
Ref:
https://github.com/spacetelescope/hstcal/issues/325
=> hstcal: Add visual verification of linkage

jwst/meta.yaml
Implements https://github.com/spacetelescope/jwst/pull/2326
=> jwst: Normalize build and run dependencies

photutils/meta.yaml
https://github.com/astroconda/astroconda-contrib/pull/387
=> Update photutils recipe

pyregion/meta.yaml, stsci-hst/meta.yaml
=> Deprecate pyregion

semantic_version/bld.bat, semantic_version/build.sh, semantic_version/meta.yaml
=> Initial commit of semantic_version

pyopengl-accelerate/bld.bat, pyopengl-accelerate/build.sh, pyopengl-accelerate/meta.yaml, pyopengl/bld.bat, pyopengl/build.sh, pyopengl/meta.yaml
=> Initial commit of pyopengl

stsci_rtd_theme/meta.yaml
This fixes some formatting issues with ordered and unordered lists
=> update stsci_rtd_theme to 0.0.2 release

webbpsf-data/build.sh, webbpsf-data/meta.yaml
=> webbpsf-data: Prevent spurious 'work/' directory

drizzlepac/meta.yaml
* Add acstools
* Remove stsci.convolve
=> drizzlepac: Fix dependencies

specviz/build.sh, specviz/meta.yaml
Removed replacement commands for patching install requirements. Added asteval and click requirements to recipe.
=> Updates to recipe and build script

drizzlepac/bld.bat, drizzlepac/build.sh, drizzlepac/meta.yaml
ref https://github.com/spacetelescope/drizzlepac/pull/349
=> drizzlepac: update recipe

acstools/bld.bat, acstools/build.sh, acstools/meta.yaml, pysynphot/bld.bat, pysynphot/build.sh, pysynphot/meta.yaml
=> Fix a few broken packages
